kind: Deployment
apiVersion: apps/v1
metadata:
  {{- $deploymentName := printf "%s-agent" (include "helloworldhelm.name" .) }}
  name: {{ $deploymentName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "helloworldhelm.name" . }}
    chart: {{ template "helloworldhelm.chart" . }}
    release: {{ .Release.Name }}
    clusterName: {{ .Values.clusterName }}
    addonInstallNamespace: {{ .Values.addonInstallNamespace }}
  annotations:
    kubeVersion: {{ .Capabilities.KubeVersion }}
    "addon.open-cluster-management.io/deletion-orphan": ""
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "helloworldhelm.name" . }}
      chart: {{ template "helloworldhelm.chart" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "helloworldhelm.name" . }}
        chart: {{ template "helloworldhelm.chart" . }}
        release: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ template "helloworldhelm.name" . }}-agent-sa
      volumes:
      - name: hub-config
        secret:
          secretName: {{ .Values.hubKubeConfigSecret }}
      {{- if .Values.tolerations }}
      tolerations: {{ toYaml .Values.tolerations | nindent 8 }}
      {{- end }}
      {{- if .Values.global.nodeSelector }}
      nodeSelector: {{ toYaml .Values.global.nodeSelector | nindent 8 }}
      {{- end }}
      containers:
      {{- $containerName := printf "%s-agent" (include "helloworldhelm.name" .) }}
      - name: {{ $containerName }}
        image: {{ .Values.global.imageOverrides.helloWorldHelm }}
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        {{- $containerID := printf "deployments:%s:%s" $deploymentName $containerName }}
        {{- $reverseResourceRequirements := reverse .Values.global.resourceRequirements }}
        {{- range $item := $reverseResourceRequirements }}
          {{- if regexMatch $item.containerIDRegex $containerID }}
        resources:
            {{- toYaml $item.resources | nindent 10 }}
            {{- break -}}
          {{- end -}}
        {{- end }}
        {{- if or .Values.global.proxyConfig.HTTP_PROXY .Values.global.proxyConfig.HTTPS_PROXY }}
        env:
          {{- if .Values.global.proxyConfig.HTTP_PROXY }}
          - name: HTTP_PROXY
            value: {{ .Values.global.proxyConfig.HTTP_PROXY }}
          {{- end }}
          {{- if .Values.global.proxyConfig.HTTPS_PROXY }}
          - name: HTTPS_PROXY
            value: {{ .Values.global.proxyConfig.HTTPS_PROXY }}
          {{- end }}
          {{- if .Values.global.proxyConfig.NO_PROXY }}
          - name: NO_PROXY
            value: {{ .Values.global.proxyConfig.NO_PROXY }}
          {{- end }}
        {{- end }}
        args:
          - "/helloworld_helm"
          - "agent"
          - "--hub-kubeconfig=/var/run/hub/kubeconfig"
          - "--cluster-name={{ .Values.clusterName }}"
          - "--addon-namespace={{ .Values.addonInstallNamespace }}"
        volumeMounts:
          - name: hub-config
            mountPath: /var/run/hub
      {{- if .Values.global.imagePullSecret }}
      imagePullSecrets:
        - name: "{{ .Values.global.imagePullSecret }}"
      {{- end }}
