kind: Job
apiVersion: batch/v1
metadata:
  {{- $jobName := printf "%s-cleanup-configmap" (include "helloworldhelm.name" .) }}
  name: {{ $jobName }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "addon.open-cluster-management.io/addon-pre-delete": ""
spec:
  manualSelector: true
  selector:
    matchLabels:
      job: {{ template "helloworldhelm.name" . }}-cleanup-configmap
  template:
    metadata:
      labels:
        job: {{ template "helloworldhelm.name" . }}-cleanup-configmap
    spec:
      serviceAccountName: {{ template "helloworldhelm.name" . }}-agent-sa
      restartPolicy: Never
      containers:
      {{- $containerName := printf "%s-agent" (include "helloworldhelm.name" .) }}
      - name: {{ $containerName }}
        image: {{ .Values.global.imageOverrides.helloWorldHelm }}
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        {{- $containerID := printf "jobs:%s:%s" $jobName $containerName }}
        {{- $reverseResourceRequirements := reverse .Values.global.resourceRequirements }}
        {{- range $item := $reverseResourceRequirements }}
          {{- if regexMatch $item.containerIDRegex $containerID }}
        resources:
            {{- toYaml $item.resources | nindent 10 }}
            {{- break -}}
          {{- end -}}
        {{- end }}
        args:
          - "/helloworld_helm"
          - "cleanup"
          - "--addon-namespace={{ .Values.addonInstallNamespace }}"
      {{- if .Values.global.imagePullSecret }}
      imagePullSecrets:
        - name: "{{ .Values.global.imagePullSecret }}"
      {{- end }}
