org: open-cluster-management.io

nameOverride: null

clusterName: null
addonInstallNamespace: null
hubKubeConfigSecret: null

tolerations: []

global:
  imagePullPolicy: IfNotPresent
  imagePullSecret: null
  imageOverrides:
    helloWorldHelm: quay.io/open-cluster-management/addon-examples:latest
  nodeSelector: {}
  proxyConfig:
    HTTP_PROXY: null
    HTTPS_PROXY: null
    NO_PROXY: null
  resourceRequirements:
  - containerIDRegex: ^.+:.+:.+$
    resources:
      requests:
        memory: 32Mi
      limits:
        memory: 128Mi
